spring:
  application:
    name: ModulithApplication

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: dev

  jpa:
    hibernate:
      ddl-auto: create-drop

#  modulith:
#    events:
#      completion-mode: ARCHIVE
#      jdbc:
#        schema-initialization:
#          enabled: true


server:
  port: 8080

logging:
  level:
    org.springframework.modulith.events: DEBUG
